name:                buttplug-hs-core
version:             0.2.0.0
github:              "sullyj3/buttplug-hs-core"
license:             BSD3
author:              "James Sully"
maintainer:          "sullyj3@gmail.com"
copyright:           "2020-2021 James Sully"
category:            Hardware
synopsis:            Client library for buttplug.io

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Library for writing clients for the Buttplug Intimate Device Control Standard. (<https://buttplug.io/>)


dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.12.0 && < 0.12
- aeson >= 1.5.5.1 && < 2.1
- aeson-casing >= 0.2.0.0 && < 0.3
- connection >= 0.3.1 && < 0.4
- network >= 3.1.1.1 && < 3.2
- text >= 1.2.4.1 && < 1.3
- containers >= 0.6.2.1 && < 0.7
- unordered-containers >= 0.2.13.0 && < 0.3
- websockets >= 0.12.7.2 && < 0.13

library:
  source-dirs: src

executables:
  buttplug-example:
    main:                example.lhs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - buttplug-hs-core
    - async >= 1.1.18 && < 2.3

tests:
  buttplug-hs-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec >= 2.7.8 && < 2.9
    - buttplug-hs-core
    - aeson-pretty >= 0.8.8 && < 0.9
    - QuickCheck >= 2.14.2 && < 2.15
    - quickcheck-instances >= 0.3.25.2 && < 0.4
    - generic-random >= 1.3.0.1 && < 1.6
    - raw-strings-qq ==1.1.*
